### PR TITLE
fix transaction id generator

### LINKED ISSUE #352: TransactionIdGenerator.getNextId - Missing starting value for integer.
https://github.com/Polidea/FlutterBleLib/blob/3507cbc5952b358908d42fdb13a70087a708e6b2/lib/internal/util/transaction_id_generator.dart#L2

This should have a default value. Otherwise `NoSuchMethodError: The method '+' was called on null.`
```dart
static int _id = 0;
```

### PR DESCRIPTION
**Pull request by pawelByszewski**
fixes #352

### CODE REVIEW

File: test/internal/util/transcation_id_generator_test.dart [hunk 1]
```diff
@@ -0,0 +1,9 @@
+
+import 'package:flutter_test/flutter_test.dart';
+import 'package:flutter_ble_lib/internal/util/transaction_id_generator.dart';
+
+void main() {
+  test("should be able to generate an id", () {
+    expect(TransactionIdGenerator.getNextId(), isNotNull);
+  });
+}
```
Comment (dariuszseweryn) [inline test/internal/util/transcation_id_generator_test.dart]: Maybe also check if next call will not return the previous result?

Comment (bartoszwilk) [reply test/internal/util/transcation_id_generator_test.dart]: I added a test that checks if next invocation returns incremented id so it also covers your case.

Comment (pawelByszewski) [reply test/internal/util/transcation_id_generator_test.dart]: The generator needs more test but this time I added test only for the fixed scenario with full determination.
